import type { HighLevelHeaderOverrides, HighLevelControlOverrides } from './batch/batchTypes.js';
import type { HighLevelAddendaFieldOverrides } from './entry-addenda/entryAddendaTypes.js';
import type { HighLevelFieldOverrides } from './entry/entryTypes.js';
export declare const highLevelAddendaFieldOverrides: Array<HighLevelAddendaFieldOverrides>;
export declare const highLevelAddendaFieldOverrideSet: Set<HighLevelAddendaFieldOverrides>;
export declare const highLevelFieldOverrides: Array<HighLevelFieldOverrides>;
export declare const highLevelFieldOverrideSet: Set<HighLevelFieldOverrides>;
export declare const highLevelHeaderOverrides: Array<HighLevelHeaderOverrides>;
export declare const highLevelHeaderOverrideSet: Set<HighLevelHeaderOverrides>;
export declare const highLevelControlOverrides: Array<HighLevelControlOverrides>;
export declare const highLevelControlOverrideSet: Set<HighLevelControlOverrides>;
